"""add auth and player contact fields

Revision ID: 2255d9e9e637
Revises: 30e942628b5a
Create Date: 2026-08-08 08:00:33.816356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2255d9e9e637'
down_revision: Union[str, None] = '30e942628b5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('email', sa.Text(), nullable=True))
    op.add_column('players', sa.Column('phone_number', sa.Text(), nullable=True))
    op.alter_column('players', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('players', 'position',
               existing_type=postgresql.ENUM('GK', 'CB', 'FB', 'DM', 'CM', 'AM', 'WNG', 'ST', name='player_position'),
               nullable=True)
    op.add_column('users', sa.Column('hashed_password', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    op.alter_column('players', 'position',
               existing_type=postgresql.ENUM('GK', 'CB', 'FB', 'DM', 'CM', 'AM', 'WNG', 'ST', name='player_position'),
               nullable=False)
    op.alter_column('players', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('players', 'phone_number')
    op.drop_column('players', 'email')
    # ### end Alembic commands ###
