"""add player weekly distance log

Revision ID: 27479c8b5d7a
Revises: e5779f382b44
Create Date: 2026-08-10 07:19:26.013239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27479c8b5d7a'
down_revision: Union[str, None] = 'e5779f382b44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_weekly_distance_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('training_cycle_id', sa.UUID(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('match_distance_km', sa.Numeric(precision=6, scale=2), server_default='0', nullable=False),
    sa.Column('training_distance_km', sa.Numeric(precision=6, scale=2), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_cycle_id'], ['training_cycles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'player_id', name='player_weekly_distance_log_match_id_player_id_key')
    )
    op.create_index(op.f('ix_player_weekly_distance_log_player_id'), 'player_weekly_distance_log', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_weekly_distance_log_player_id'), table_name='player_weekly_distance_log')
    op.drop_table('player_weekly_distance_log')
    # ### end Alembic commands ###
