"""initial schema

Revision ID: 30e942628b5a
Revises: 
Create Date: 2026-08-08 07:47:52.557908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30e942628b5a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('create extension if not exists "uuid-ossp"')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('primary_color', sa.Text(), nullable=True),
    sa.Column('secondary_color', sa.Text(), nullable=True),
    sa.Column('competition_level', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('matches',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('opponent', sa.Text(), nullable=False),
    sa.Column('match_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('competition', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('scheduled', 'played', 'postponed', 'cancelled', name='match_status'), server_default='scheduled', nullable=False),
    sa.Column('postponed_reason', sa.Text(), nullable=True),
    sa.Column('rescheduled_to', sa.UUID(), nullable=True),
    sa.Column('final_score_for', sa.Integer(), nullable=True),
    sa.Column('final_score_against', sa.Integer(), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rescheduled_to'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('auth_user_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('role', postgresql.ENUM('admin', 'head_coach', 'assistant_coach', 'physio', 'analyst', 'player', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('players',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('position', postgresql.ENUM('GK', 'CB', 'FB', 'DM', 'CM', 'AM', 'WNG', 'ST', name='player_position'), nullable=False),
    sa.Column('dominant_foot', sa.Text(), nullable=True),
    sa.Column('jersey_number', sa.Integer(), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("dominant_foot in ('left','right','both')", name='players_dominant_foot_check'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_cycles',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('length_type', postgresql.ENUM('4_weeks', '6_weeks', '8_weeks', name='cycle_length'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('target_match_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('shift_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mas_tests',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('test_date', sa.Date(), nullable=False),
    sa.Column('protocol', sa.Text(), server_default='30-15 IFT', nullable=False),
    sa.Column('mas_kmh', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('vo2max_estimate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('hr_max_bpm', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_minutes',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('minutes_played', sa.Integer(), server_default='0', nullable=False),
    sa.Column('started_match', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('substituted_in_min', sa.Integer(), nullable=True),
    sa.Column('substituted_out_min', sa.Integer(), nullable=True),
    sa.Column('position_played', postgresql.ENUM('GK', 'CB', 'FB', 'DM', 'CM', 'AM', 'WNG', 'ST', name='player_position'), nullable=True),
    sa.Column('distance_total_m', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('distance_hsr_m', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('sprints_count', sa.Integer(), nullable=True),
    sa.Column('top_speed_kmh', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'player_id', name='match_minutes_match_id_player_id_key')
    )
    op.create_table('rpe_wellness_data',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('session_type', sa.Text(), nullable=True),
    sa.Column('rpe_score', sa.Integer(), nullable=True),
    sa.Column('session_duration_min', sa.Integer(), nullable=True),
    sa.Column('session_load', sa.Integer(), sa.Computed('rpe_score * session_duration_min', persisted=True), nullable=True),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('fatigue_level', sa.Integer(), nullable=True),
    sa.Column('muscle_soreness', sa.Integer(), nullable=True),
    sa.Column('stress_level', sa.Integer(), nullable=True),
    sa.Column('mood', sa.Integer(), nullable=True),
    sa.Column('injury_flag', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('injury_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('fatigue_level between 1 and 5', name='rpe_wellness_data_fatigue_level_check'),
    sa.CheckConstraint('mood between 1 and 5', name='rpe_wellness_data_mood_check'),
    sa.CheckConstraint('muscle_soreness between 1 and 5', name='rpe_wellness_data_muscle_soreness_check'),
    sa.CheckConstraint('rpe_score between 1 and 10', name='rpe_wellness_data_rpe_score_check'),
    sa.CheckConstraint('sleep_quality between 1 and 5', name='rpe_wellness_data_sleep_quality_check'),
    sa.CheckConstraint('stress_level between 1 and 5', name='rpe_wellness_data_stress_level_check'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'entry_date', 'session_type', name='rpe_wellness_data_player_id_entry_date_session_type_key')
    )
    op.create_table('training_cycle_weeks',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('training_cycle_id', sa.UUID(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('focus', postgresql.ENUM('accumulation', 'intensification', 'realization', 'deload', 'recovery', name='week_focus'), nullable=False),
    sa.Column('planned_load_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['training_cycle_id'], ['training_cycles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('training_cycle_id', 'week_number', name='training_cycle_weeks_training_cycle_id_week_number_key')
    )
    # ### end Alembic commands ###

    op.execute(
        """
        create view current_mas as
        select distinct on (player_id)
            player_id, mas_kmh, test_date, protocol
        from mas_tests
        order by player_id, test_date desc
        """
    )


def downgrade() -> None:
    op.execute("drop view if exists current_mas")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_cycle_weeks')
    op.drop_table('rpe_wellness_data')
    op.drop_table('match_minutes')
    op.drop_table('mas_tests')
    op.drop_table('training_cycles')
    op.drop_table('players')
    op.drop_table('users')
    op.drop_table('matches')
    op.drop_table('clubs')
    # ### end Alembic commands ###

    for enum_name in ("week_focus", "cycle_length", "player_position", "user_role", "match_status"):
        op.execute(f"drop type if exists {enum_name}")
