"""add training_sessions table

Revision ID: 4fe8e2b0f5dd
Revises: 5bf7f5ea9851
Create Date: 2026-08-10 16:14:26.464448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4fe8e2b0f5dd'
down_revision: Union[str, None] = '5bf7f5ea9851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column(
        'week_focus',
        postgresql.ENUM(
            'accumulation', 'intensification', 'realization', 'deload', 'recovery',
            name='week_focus', create_type=False,
        ),
        nullable=False,
    ),
    sa.Column('target_duration_min', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('target_distance_km', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_sessions')
    # ### end Alembic commands ###
