"""add target_match_date and calendar tables

Revision ID: 5bf7f5ea9851
Revises: 27479c8b5d7a
Create Date: 2026-08-10 08:23:53.397999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bf7f5ea9851'
down_revision: Union[str, None] = '27479c8b5d7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('is_projected', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_events_event_date'), 'calendar_events', ['event_date'], unique=False)
    op.create_table('calendar_event_players',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('calendar_event_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_event_id'], ['calendar_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_event_players_calendar_event_id'), 'calendar_event_players', ['calendar_event_id'], unique=False)
    op.add_column('training_cycles', sa.Column('target_match_date', sa.Date(), nullable=True))
    # existing cycles predate this column; backfill with end_date as a synthetic default
    op.execute("UPDATE training_cycles SET target_match_date = end_date WHERE target_match_date IS NULL")
    op.alter_column('training_cycles', 'target_match_date', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_cycles', 'target_match_date')
    op.drop_index(op.f('ix_calendar_event_players_calendar_event_id'), table_name='calendar_event_players')
    op.drop_table('calendar_event_players')
    op.drop_index(op.f('ix_calendar_events_event_date'), table_name='calendar_events')
    op.drop_table('calendar_events')
    # ### end Alembic commands ###
