"""add platform_admins and club_modules

Revision ID: 6cea37cb8bb9
Revises: 4fe8e2b0f5dd
Create Date: 2026-08-12 07:43:36.985760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6cea37cb8bb9'
down_revision: Union[str, None] = '4fe8e2b0f5dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_admins',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('club_modules',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('module_key', postgresql.ENUM('dashboard', 'squad_overview', 'mas_compensatie', 'next_training', 'kalender', 'mas_test', 'return_to_play', 'video_analyse', name='module_key'), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('changed_by', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'module_key', name='club_modules_club_id_module_key_key')
    )
    # ### end Alembic commands ###

    # Backfill: every club that existed before this migration gets the base
    # package activated, matching services.platform_admin.activate_base_package().
    # Without this, is_module_enabled_for_club() (default-deny for anything
    # without a club_modules row) would lock every pre-existing club out of
    # everything except the core Dashboard module the moment the module-gating
    # dependency goes live.
    conn = op.get_bind()
    base_package_modules = [
        "dashboard", "squad_overview", "mas_compensatie", "next_training",
        "kalender", "mas_test", "return_to_play",
    ]
    club_ids = [row[0] for row in conn.execute(sa.text("SELECT id FROM clubs")).fetchall()]
    for club_id in club_ids:
        for module_key in base_package_modules:
            conn.execute(
                sa.text(
                    "INSERT INTO club_modules (club_id, module_key, enabled, changed_by) "
                    "VALUES (:club_id, :module_key, true, :changed_by)"
                ),
                {"club_id": club_id, "module_key": module_key, "changed_by": "migratie: basispakket backfill"},
            )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('club_modules')
    op.drop_table('platform_admins')
    # ### end Alembic commands ###
