"""add selection_status to match_minutes

Revision ID: e5779f382b44
Revises: b7ba1fe24931
Create Date: 2026-08-09 20:20:18.587303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5779f382b44'
down_revision: Union[str, None] = 'b7ba1fe24931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_minutes', sa.Column('selection_status', sa.Text(), server_default='basis', nullable=False))
    # ### end Alembic commands ###
    op.create_check_constraint(
        'match_minutes_selection_status_check',
        'match_minutes',
        "selection_status in ('basis','bank','niet_geselecteerd')",
    )


def downgrade() -> None:
    op.drop_constraint('match_minutes_selection_status_check', 'match_minutes', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_minutes', 'selection_status')
    # ### end Alembic commands ###
